### ISSUE TITLE
Error: Not found: Job <project_id>:<job_id>

### ISSUE THREAD

**Issue by caioricciuti** [googleapis/nodejs-bigquery#1016]
https://github.com/googleapis/nodejs-bigquery/issues/888

#### Environment details

  - OS: MACOS
  - Node.js version: 14
  - npm version:
  - `@google-cloud/bigquery` version: 5.9.0

#### Steps to reproduce

Cloud Function: 

```js
const { BigQuery } = require("@google-cloud/bigquery");
const bigquery = new BigQuery();

exports.myFunction = async (req, res) => {

  const query = `SELECT name
      FROM \`<project_id>.<data_set_name>.<table_name>\`
      WHERE TRUE
      LIMIT 100`;

  const options = {
    query: query,
    location: "europe-west3",
  };

  // Run the query as a job
  const [job] = await bigquery.createQueryJob(options);
  console.log(`Job ${job.id} started.`);

  // Wait for the query to finish
  const [rows] = await job.getQueryResults();

  // Print the results
  console.log("Rows:");
  rows.forEach((row) => console.log(row));

  res.status(200).send('ok')
};
```

Error: 
```
Error: Not found: Job <project_id>:<job_id> at new ApiError (/workspace/node_modules/@google-cloud/common/build/src/util.js:73:15) at Util.parseHttpRespBody (/workspace/node_modules/@google-cloud/common/build/src/util.js:208:38) at Util.handleResp (/workspace/node_modules/@google-cloud/common/build/src/util.js:149:117) at /workspace/node_modules/@google-cloud/common/build/src/util.js:477:22 at onResponse (/workspace/node_modules/retry-request/index.js:228:7) at /workspace/node_modules/teeny-request/build/src/index.js:226:13 at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

This started to happen today in the morning... I've no clue what is causing it. Can someone tell me if it is a google's problem? I believe my code is right since it was working and this morning it stopped. 

Thanks in advance!

**Comment by danunafig** [comment]
Same here. 

Environment details
- Node.js version: 14
- npm version:
- @google-cloud/bigquery version: 5.9.0

`
const {
  BigQuery
} = require('@google-cloud/bigquery');

// Instantiate clients
const bigquery = new BigQuery();

async function run() {
  const options = {
    maxResults: 1
  };
  const [jobs] = await bigquery.getJobs(options);

  let jobId = '';
  jobs.forEach(job => {
    jobId = job.id
  });
  console.log(`Job Id: ${jobId}`)  // Got the JjobId 

  // Try to use it. Failed
  const job = bigquery.job(jobId);
  const [jobResult] = await job.get();
}

(async () => {
  run();
})();
`

Got an error "ApiError: Not found: Job <JobID>"
Tried with and without project prefix, region. Nothing helps.

**Comment by danunafig** [comment]
Hm, today same code works fine. Have no idea what google did

**Comment by danunafig** [comment]
Basically using job.id from the job list (bigquery.getJobs) won't help in bigquery.job(jobId).

**Comment by meredithslota** [comment]
The first example (https://github.com/googleapis/nodejs-bigquery/issues/1016#issue-1002261756) almost perfectly matches our code sample from this page: https://cloud.google.com/bigquery/docs/running-queries#bigquery-query-api which makes me think it _should_ be working, but I'm wondering if it's an issue elsewhere. I'll ask @steffnay to look into this. Thanks for filing!

**Comment by danunafig** [comment]
You can try this one from
https://googleapis.dev/nodejs/bigquery/latest/Job.html#get
I guess it could be related to the job location.

`const { BigQuery } = require('@google-cloud/bigquery');

const bigquery = new BigQuery();

async function run() {
  const options = { maxResults: 1 };
  const [jobs] = await bigquery.getJobs(options);

  jobs.map(async (job) => {
    console.log(job.id)
    const jobRef = bigquery.job(job.id);
    try {
      await jobRef.get();
    } catch(e) {
      console.error(e.message);
    }
  });

}

(async () => {
  run();
})();`

**Comment by danunafig** [comment]
Still there.  Did you try bigquery jobs from another location? My jobs are running in eu-3 (Frankfurt).

What is the JobID format for calling ```bigquery.job()``` .  I think it can be related, as getJobs() returns <UUID>, but bigquery.job() is looking for <ProjectId>:<UUID>

Did you get a job back using my snippet?

**Comment by caioricciuti** [comment]
@danunafig, thank you for your message, I don't get this error anymore, but I was not the one who fix it, I had someone in my team who change the cloud function. But when I use the code I wrote (the original that I posted), I still get the error. 

Thanks!

**Comment by steffnay** [comment]
That is correct behavior. I meant please try updating the location of the client in order to see if it fixes your issue.
```
const bigquery = new BigQuery();

async function run() {
  const options = { maxResults: 1 };
  const [jobs] = await bigquery.getJobs(options);

  jobs.map(async (job) => {
    console.log(job.id)
    const jobRef = bigquery.job(job.id);
    bigquery.location = job.location
    try {
      await jobRef.get();
    } catch(e) {
      console.error(e.message);
    }
  });

}

(async () => {
  run();
})();
```

**Comment by danunafig** [comment]
Sorry,  I don't agree. You can get the list of BQ jobs from any location, but to get a single job from the same list you have to change the location of the client. :) Don't you think it is a little bit strange? If jobId is unique, why should it be the same location, if it is not, why I cannot specify the job location, as it is in list metadata?

**Comment by steffnay** [comment]
Oh, I'm sorry, I reread your commend and realized I initially misunderstood. You can also pass the job location into the `Job.get(`) call via options. Does this solve the issue:

```
const bigquery = new BigQuery();

async function run() {
  const options = { maxResults: 1 };
  const [jobs] = await bigquery.getJobs(options);

  jobs.map(async (job) => {
    console.log(job.id)
    const jobRef = bigquery.job(job.id);
    try {
      // Provide location via options
      await jobRef.get({location: job.location});
    } catch(e) {
      console.error(e.message);
    }
  });

}

(async () => {
  run();
})();
```

**Comment by danunafig** [comment]
It worked with extra options.  Thank you. 
Documentation is not updated  :)
https://googleapis.dev/nodejs/bigquery/latest/Job.html#get
