### ISSUE TITLE
NUMERIC type data receiving extra decimal digit on insertRow request

### ISSUE THREAD

**Issue by DaniloTeo** [googleapis/nodejs-bigquery#1221]
#### Environment details

  - OS: MacOS Monterey 12.6
  - Node.js version: 18.15
  - npm version: 9.5.0
  - `@google-cloud/bigquery` version: ^6.1.0

#### Steps to reproduce

  1. Create a table with a column named `test_col` with `NUMERIC` type
  2. run this snippet (assuming credentials for GCP are in place)
  ```js
  const { BigQuery } = require('@google-cloud/bigquery')
  const bigQueryClient = new BigQuery()
  return bigQueryClient
          .dataset({{yourDatasetId}})
          .table({{yourTableId}})
          .insert({
            test_col: 1255139.628052805
          })
  ```
One should get an erro similar to the one below:
```sh
PartialFailureError
    at Table._insert (/Users/suprisul/Documents/eng/lemoncake-infra/node_modules/@google-cloud/bigquery/build/src/table.js:1118:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Table._insertWithRetry (/Users/suprisul/Documents/eng/lemoncake-infra/node_modules/@google-cloud/bigquery/build/src/table.js:1052:24)
    at async Table._insertAndCreateTable (/Users/suprisul/Documents/eng/lemoncake-infra/node_modules/@google-cloud/bigquery/build/src/table.js:1014:20) {
  errors: [
    {
      errors: [
        {
          message: 'Invalid NUMERIC value: 1255139.6280528051',
          reason: 'invalid'
        }
      ],
      row: {
        test_col: 1255139.628052805,
      }
    }
  ],
  response: {
    kind: 'bigquery#tableDataInsertAllResponse',
    insertErrors: [
      {
        index: 0,
        errors: [
          {
            reason: 'invalid',
            location: 'test_col',
            debugInfo: '',
            message: 'Invalid NUMERIC value: 1255139.6280528051'
          }
        ]
      }
    ]
  }
}

```

Thanks in advance!

**Comment by alvarowolfx** [comment]
For NUMERIC types, you need to send as a `STRING` or using the Big.js package. Sending numeric values this way is safer and avoids precision problems by using the float type.

```
const { BigQuery } = require('@google-cloud/bigquery')
const bigQueryClient = new BigQuery()
return bigQueryClient
        .dataset({{yourDatasetId}})
        .table({{yourTableId}})
        .insert({
          test_col: '1255139.628052805'
        })
```
OR
```
const Big = require('big.js');
const { BigQuery } = require('@google-cloud/bigquery')
const bigQueryClient = new BigQuery()
return bigQueryClient
        .dataset({{yourDatasetId}})
        .table({{yourTableId}})
        .insert({
          test_col: new Big('1255139.628052805')
        })
```

I've tested with both methods and worked just fine.

**Comment by DaniloTeo** [comment]
Hi there, @alvarowolfx.
Went with the string approach and this seems to have solved my problem.
Thank you!
