### ISSUE TITLE
TypeError: Cannot read property 'constructor' of null during insert

### ISSUE THREAD

**Issue by swftvsn** [googleapis/nodejs-bigquery#15]
#### Environment details
Running in Firebase Cloud Functions

  - `@google-cloud/bigquery` version: 0.11.0

#### Steps to reproduce

Feed any object containing null values to insert function like this: 

```ts
  const BigQuery = require('@google-cloud/bigquery')
  const bq = BigQuery({ projectId: 'prjctd' })

  bq
    .dataset('ds')
    .table('tbl')
    .insert([{
      'first': 'A value',
      'second': null
    }])

```
Here is the stacktrace:
```
TypeError: Cannot read property 'constructor' of null
    at Function.Table.encodeValue_ (/user_code/node_modules/@google-cloud/bigquery/src/table.js:286:30)
    at /user_code/node_modules/@google-cloud/bigquery/src/table.js:303:24
    at Array.reduce (native)
    at Function.Table.encodeValue_ (/user_code/node_modules/@google-cloud/bigquery/src/table.js:302:31)
    at /user_code/node_modules/@google-cloud/bigquery/src/table.js:1027:21
    at Array.map (native)
    at Table.insert (/user_code/node_modules/@google-cloud/bigquery/src/table.js:1025:30)
    at /user_code/node_modules/@google-cloud/bigquery/node_modules/@google-cloud/common/src/util.js:753:22
    at Table.wrapper [as insert] (/user_code/node_modules/@google-cloud/bigquery/node_modules/@google-cloud/common/src/util.js:737:12)
    at BigQueryService.insertStuff (/user_code/index.js:2992:14)
```

Looking at the `Table.encodeValue_` function there propably should be simple check like this at the beginning of the function:

```ts
if (value === undefined || value === null) {
  return null
}
```

**Comment by swftvsn** [comment]
PR #16
