### ISSUE TITLE
documented example return error.

### ISSUE THREAD

**Issue by vinaymavi** [googleapis/nodejs-bigquery#179]
Given Example
```
const BigQuery = require('@google-cloud/bigquery');
const bigquery = new BigQuery();

const query = 'SELECT url FROM `publicdata:samples.github_nested` LIMIT 100';

bigquery.query(query, function(err, rows) {
  if (!err) {
    // rows is an array of results.
  }
});
```

Return Error 
```
{ ApiError: Project name needs to be separated by dot from dataset name, not by colon in table name "publicdata:samples.github_nested".
    at Object.parseHttpRespBody (/Users/vinkumar8/bitbucket/bnifsc/command-line/node_modules/@google-cloud/common/src/util.js:193:30)
    at Object.handleResp (/Users/vinkumar8/bitbucket/bnifsc/command-line/node_modules/@google-cloud/common/src/util.js:131:18)
    at /Users/vinkumar8/bitbucket/bnifsc/command-line/node_modules/@google-cloud/common/src/util.js:496:12
    at Request.onResponse [as _callback] (/Users/vinkumar8/bitbucket/bnifsc/command-line/node_modules/retry-request/index.js:198:7)
    at Request.self.callback (/Users/vinkumar8/bitbucket/bnifsc/command-line/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/vinkumar8/bitbucket/bnifsc/command-line/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
  code: 400,
  errors:
   [ { message: 'Project name needs to be separated by dot from dataset name, not by colon in table name "publicdata:samples.github_nested".',
       domain: 'global',
       reason: 'invalidQuery',
       location: 'parameters.q' } ],
  response: undefined,
  message: 'Project name needs to be separated by dot from dataset name, not by colon in table name "publicdata:samples.github_nested".' }
```

**Comment by stephenplusplus** [comment]
Thanks for the heads up! PR sent: #180
