### ISSUE TITLE
Samples result in error: TypeError: BigQuery is not a constructor

### ISSUE THREAD

**Issue by jasonpolites** [googleapis/nodejs-bigquery#284]
#### Environment details

  - OS: Linux (GCP Cloud Shell)
  - Node.js version: v8.9.4
  - npm version:5.6.0
  - `@google-cloud/bigquery` version: 2.0.1

#### Steps to reproduce

**index.js**
```Javascript
const BigQuery = require('@google-cloud/bigquery');
const bigquery = new BigQuery();
```

**Command Line**
```
node index.js
```

**Result**
```
TypeError: BigQuery is not a constructor
    at Object.<anonymous> (/[REDACTED]/index.js:7:18)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by JustinBeckwith** [comment]
The right syntax here now is:

```js
const {BigQuery} = require('@google-cloud/bigquery');
const bigquery = new BigQuery();
```

Can you point us towards the sample you're using?  We may need to just update that.

**Comment by JustinBeckwith** [comment]
Ok - the problem here is that the 2.x BigQuery docs weren't published :(
https://cloud.google.com/nodejs/docs/reference/bigquery/1.3.x/Dataset#table

**Comment by kinwa91** [comment]
2.x docs are published!
