### ISSUE TITLE
Cannot call table.createLoadJob using file from storage client

### ISSUE THREAD

**Issue by josselin-arcane** [googleapis/nodejs-bigquery#357]
- Search the issues already opened: https://github.com/googleapis/nodejs-bigquery/issues -> I have not found related issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node -> Found this that seems related https://github.com/googleapis/google-cloud-node/issues/1516
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js -> Not found

#### Environment details

  - OS: Docker image launcher.gcr.io/google/nodejs
  - Node.js version: 10.15.1
  - npm version: 6.4.1 or 6.8.0
  - `@google-cloud/bigquery` version: 2.0.6 (but tried several)
  - `@google-cloud/storage` version: 2.0.6 (but tried several)

#### Steps to reproduce

```
const { Storage } = require('@google-cloud/storage')
storage = new Storage()

const { BigQuery } = require('@google-cloud/bigquery'}
const bigquery = new BigQuery()
const table = bigquery.dataset(<datasetId>).table(<tableId>)

const file = storage.bucket(bucketName).file(filePath)
await table.load({ source: file }) // Triggers stack trace below
```

Stack trace : 
```
TypeError: x.trim is not a function
    at reqOpts.uri.uriComponents.filter.x (/app/node_modules/@google-cloud/common/build/src/service-object.js:213:28)
    at Array.filter (<anonymous>)
    at Job.request_ (/app/node_modules/@google-cloud/common/build/src/service-object.js:213:14)
    at Job.request (/app/node_modules/@google-cloud/common/build/src/service-object.js:231:14)
    at Job.cancel (/app/node_modules/@google-cloud/bigquery/build/src/job.js:256:14)
    at PromiseCtor (/app/node_modules/@google-cloud/promisify/build/src/index.js:71:28)
    at new Promise (<anonymous>)
    at Job.wrapper (/app/node_modules/@google-cloud/promisify/build/src/index.js:56:16)
    at exports.cancelJob.jobId (/app/scheduler/libs/schedulerLib.js:59:14)
    at exports.main (/app/scheduler/index.js:29:7)
Error: Source must be a File object.
    at extend.sourceUris.arrify.map (/app/node_modules/@google-cloud/bigquery/build/src/table.js:812:27)
    at Array.map (<anonymous>)
    at Table.createLoadJob (/app/node_modules/@google-cloud/bigquery/build/src/table.js:810:40)
    at Table.wrapper (/app/node_modules/@google-cloud/promisify/build/src/index.js:44:35)
    at Table.load (/app/node_modules/@google-cloud/bigquery/build/src/table.js:1208:14)
    at PromiseCtor (/app/node_modules/@google-cloud/promisify/build/src/index.js:71:28)
    at new Promise (<anonymous>)
    at Table.wrapper (/app/node_modules/@google-cloud/promisify/build/src/index.js:56:16)
    at exports.launchLoadJob (/app/scheduler/libs/schedulerLib.js:24:16)
    at exports.main (/app/scheduler/index.js:28:7)
Error: Source must be a File object.
    at extend.sourceUris.arrify.map (/app/node_modules/@google-cloud/bigquery/build/src/table.js:812:27)
    at Array.map (<anonymous>)
    at Table.createLoadJob (/app/node_modules/@google-cloud/bigquery/build/src/table.js:810:40)
    at Table.wrapper (/app/node_modules/@google-cloud/promisify/build/src/index.js:44:35)
    at Table.load (/app/node_modules/@google-cloud/bigquery/build/src/table.js:1208:14)
    at PromiseCtor (/app/node_modules/@google-cloud/promisify/build/src/index.js:71:28)
    at new Promise (<anonymous>)
    at Table.wrapper (/app/node_modules/@google-cloud/promisify/build/src/index.js:56:16)
    at exports.launchLoadJob (/app/scheduler/libs/schedulerLib.js:24:16)
    at exports.main (/app/scheduler/index.js:28:7)
```

I have a hunch that this problem is close to this issue : https://github.com/googleapis/google-cloud-node/issues/1516

I think that storage latest version (2.4.2) and big query latest version (2.0.6) have incompatible File class definition.
I tried : 
- downgrading one of the two apis without any luck (bq 2.0.6 | gcs 2.3.4, bq 2.0.6 | gcs 2.2.0, bq 2.0.5
 | gcs 2.3.4) etc...
- I tried to install npm package google-cloud to have compatible version but I somehow get an exit status 255 for google-cloud@0.58.2 during 'preinstall'.
- I tried to find the compatible version of storage using package.json information but the version is not fixed.

Am I right in thinking this is an incompatibility of File class definition between versions?
If so what version of storage (and bigquery?) is safe to use?

Thank you for your help.

**Comment by josselin-arcane** [comment]
Hi Again,

After retrying with a fresh head and new docker build we couldn't reproduce the issue with this code. As such I will close the issue.

Sorry for the inconvenience.
