### ISSUE TITLE
End event firing before error event

### ISSUE THREAD

**Issue by shisoderohit** [googleapis/nodejs-bigquery#388]
- OS: mac OS X
  - Node.js version: 8.12.0
  - npm version: 6.4.1
  - `@google-cloud/bigquery` version: 2.1.0

When I try to use createQueryStream method on BigQuery class using legacy sql query, the end event occurs before error event when I have some error in query itself. Suppose I have following function using createQueryStream to get records for a query - 

```
var result = [];
    bigquery.createQueryStream({ useLegacySql: true, query: options.query })
        .on('error', function (err) {
            console.error(err);
            cb(err, null);
        })
        .on('data', function (row) {
            result.push(row);
        })
        .on('end', function () {
            console.log("BQ stream finished");
            cb(null, result);
        });
````
Here as evident in code, I want to call my callback with error and null value on error event and use end event when I have all data that I need and return all the rows back to callback.
Here if there is any error in query like int32 inplace of string for some value in where clause, I expected error event to be called first and not end before it, but it seems they are both getting called and also end is fired before error event!?
I am new here, so might be something wrong on my part,  but it seems like issue with events getting fired. Any help would be greatly appreciated. 
Thanx

**Comment by stephenplusplus** [comment]
Thank you for reporting. I haven't been able to reproduce using this snippet:

```js
const options = {
  query: 'SELECT url FROM [publicdata.samples.github_nested] WHERE url = 3 LIMIT 100',
  useLegacySql: true,
}

bigquery.createQueryStream(options)
  .on('data', row => {
    assert.strictEqual(typeof row.url, 'string');
  })
  .on('error', err => {
    console.log('error', err)
  })
  .on('end', () => {
    console.log('end')
  });
```

Could you check if that still fails for you, and if not, see if you can make it fail so I can dig in deeper?

**Comment by shisoderohit** [comment]
Sure, Will try and reproduce and let you know results. It is still failing for me on my dataset, will try to reproduce with public dataset

**Comment by shisoderohit** [comment]
```
const { BigQuery } = require("@google-cloud/bigquery");

(() => {
	const result = [];
	new BigQuery()
		.createQueryStream({ 
			useLegacySql: true, 
			query: "SELECT url FROM [bigquery-public-data:samples.github_nested] WHERE url=3 LIMIT 5" 
		})
		.on("error", err => {
			console.log("Error fired");
			console.error("error", err);
		})
		.on("data", row => {
			result.push(row);
		})
		.on("end", () => {
			console.log("End fired");
			console.log("END - BQ stream finished");
		});
})();
```

Here is the output - 

```
End fired
END - BQ stream finished
Error fired
error { Error: Argument type mismatch in function EQUAL: 'url' is type string, '3' is type int32
    at Util.parseHttpRespBody (/Users/zerebral/projects/API_staging/marketcheck_api/node_modules/@google-cloud/bigquery/node_modules/@google-cloud/common/build/src/util.js:190:38)
    at Util.handleResp (/Users/zerebral/projects/API_staging/marketcheck_api/node_modules/@google-cloud/bigquery/node_modules/@google-cloud/common/build/src/util.js:134:117)
    at retryRequest (/Users/zerebral/projects/API_staging/marketcheck_api/node_modules/@google-cloud/bigquery/node_modules/@google-cloud/common/build/src/util.js:422:22)
    at onResponse (/Users/zerebral/projects/API_staging/marketcheck_api/node_modules/@google-cloud/bigquery/node_modules/retry-request/index.js:200:7)
    at /Users/zerebral/projects/API_staging/marketcheck_api/node_modules/teeny-request/build/src/index.js:191:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  code: 400,
  errors: 
   [ { message: 'Argument type mismatch in function EQUAL: \'url\' is type string, \'3\' is type int32',
       domain: 'global',
       reason: 'invalidQuery',
       location: 'q',
       locationType: 'parameter' } ],
  response: undefined,
  message: 'Argument type mismatch in function EQUAL: \'url\' is type string, \'3\' is type int32' }
```
As you can see from o/p both events are getting fired and end fires before error.

**Comment by shisoderohit** [comment]
Its giving me same error for this snippet - 

```javascript
const { BigQuery } = require("@google-cloud/bigquery");

(() => {
	const result = [];
	new BigQuery()
		.createQueryStream({ 
			useLegacySql: true, 
			query: "SELECT url FROM [bigquery-public-data:samples.github_nested] WHERE url=3 LIMIT 5" 
		})
		.on("error", err => {
			console.log("Error fired");
			console.error("error", err);
		})
		.on("data", row => {
			result.push(row);
		})
		.on("end", () => {
			console.log("End fired");
			console.log("END - BQ stream finished");
		});
})();
```
Here is the output of above snippet - 
```
End fired
END - BQ stream finished
Error fired
error { Error: Argument type mismatch in function EQUAL: 'url' is type string, '3' is type int32
    at Util.parseHttpRespBody (/Users/rohit/projects/big_query_demo/node_modules/@google-cloud/common/build/src/util.js:190:38)
    at Util.handleResp (/Users/rohit/projects/big_query_demo/node_modules/@google-cloud/common/build/src/util.js:134:117)
    at retryRequest (/Users/rohit/projects/big_query_demo/node_modules/@google-cloud/common/build/src/util.js:422:22)
    at onResponse (/Users/rohit/projects/big_query_demo/node_modules/retry-request/index.js:200:7)
    at /Users/rohit/projects/big_query_demo/node_modules/teeny-request/build/src/index.js:222:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  code: 400,
  errors: 
   [ { message: 'Argument type mismatch in function EQUAL: \'url\' is type string, \'3\' is type int32',
       domain: 'global',
       reason: 'invalidQuery',
       location: 'q',
       locationType: 'parameter' } ],
  response: undefined,
  message: 'Argument type mismatch in function EQUAL: \'url\' is type string, \'3\' is type int32' }
```
As you can see from output both events get fired and end is fired before error event

**Comment by stephenplusplus** [comment]
No fix yet, but just a quick update. I believe this has to do with a dependency change we made in an underlying library. As a workaround, you could handle one or the other:

```js
const { BigQuery } = require("@google-cloud/bigquery");

const result = [];
let streamEnded = false;

new BigQuery()
    .createQueryStream({
      useLegacySql: true,
      query: "SELECT url FROM [bigquery-public-data:samples.github_nested] WHERE url=3 LIMIT 5"
    })
    .on("error", err => {
      if (streamEnded) return;
      streamEnded = true;
      console.log("Error fired");
      console.error("error", err);
    })
    .on("data", row => {
      result.push(row);
    })
    .on("end", () => {
      // setImmediate to let error event fire.
      setImmediate(() => {
        if (streamEnded) return;
        streamEnded = true;
        console.log("End fired");
        console.log("END - BQ stream finished");
      });
    });
```

Alternatively, update to Node v10 and the original code should just work :)

**Comment by callmehiphop** [comment]
@shisoderohit it has been a little while, but is this still an issue for you?

**Comment by shisoderohit** [comment]
@callmehiphop No this is not an issue for me anymore. As @stephenplusplus suggested I implemented a workaround for this and moved on. Thanks
