### ISSUE TITLE
Cannot create table from DATASTORE_BACKUP

### ISSUE THREAD

**Issue by v3n3** [googleapis/nodejs-bigquery#450]
#### Environment details

  - OS: macOS 10.14.5
  - Node.js version: 8.16.0
  - npm version: 6.4.1
  - `@google-cloud/bigquery` version: 4.0.0

#### Steps to reproduce

  I am trying to run the following cloud function (inspired by [this](https://github.com/googleapis/nodejs-bigquery/blob/master/samples/loadParquetFromGCSTruncate.js)):
```typescript
import * as functions from 'firebase-functions'
import * as dateformat from 'dateformat'
import collections from './internal/Collections'
import { BigQuery } from '@google-cloud/bigquery'

export const ImportFirestoreToBigQuery = functions.pubsub.schedule('30 4 * * *').onRun(async (_) => {
    // Construct a backup path folder based on the timestamp
    const timestamp = dateformat(Date.now(), 'yyyymmdd')
    const path = `gs://XXXXX/${timestamp}`

    const bigqueryClient = new BigQuery();
    const metadata = {
        sourceFormat: 'DATASTORE_BACKUP',
        // Set the write disposition to overwrite existing table data.
        writeDisposition: 'WRITE_TRUNCATE',
        location: 'US',
    }

    for (const collectionKey of collections.keys()) {
        // If specified, mark specific collections for backup
        const collectionParam: string[] = collections.get(collectionKey)
        if (collectionParam) {
            for (const kind of collectionParam) {
                // Load data from a Google Cloud Storage file into the table
                const [job] = await bigqueryClient
                    .dataset(`firestore_${collectionKey}`)
                    .table(collectionKey + '_' + timestamp)
                    .load(`${path}/${timestamp}/${collectionKey}/all_namespaces/kind_${kind}/all_namespaces_kind_${kind}.export_metadata
                `, metadata)
                // load() waits for the job to finish
                console.log(`Job ${job.id} completed.`)

                // Check the job's status for errors
                const errors = job.status.errors
                if (errors && errors.length > 0) {
                    console.warn(errors)
                }
            }
        }

    }
    return true
})
```
and the console returns :

```
[debug] [2019-05-22T16:51:42.015Z] DEBUG: Trigger "importFirestoreToBigQuery" has been found, beginning invocation!
[debug] [2019-05-22T16:51:42.015Z] DEBUG: 
[debug] [2019-05-22T16:51:42.015Z] DEBUG: Running importFirestoreToBigQuery in mode BACKGROUND
[debug] [2019-05-22T16:51:42.016Z] DEBUG: RunBackground: proto={"eventId":"763ea28c-d2f5-4e2c-8bf0-fff082a17535","timestamp":"2019-05-22T16:51:40.598Z","eventType":"google.pubsub.topic.publish","data":{}}
[debug] [2019-05-22T16:51:42.024Z] DEBUG: Ephemeral server survived.
[warn] ⚠  Error: Source format not recognized: DATASTORE_BACKUP
    at Table.createWriteStream_ (XXXXXXX/node_modules/@google-cloud/bigquery/build/src/table.js:1074:19)
    at Table.createLoadJob (XXXXXX/node_modules/@google-cloud/bigquery/build/src/table.js:955:28)
    at Table.wrapper (XXXXXX/node_modules/@google-cloud/bigquery/node_modules/@google-cloud/promisify/build/src/index.js:44:35)
    at Table.load (XXXXXXXXX/node_modules/@google-cloud/bigquery/build/src/table.js:1642:14)
    at PromiseCtor (XXXXXXXXX/node_modules/@google-cloud/bigquery/node_modules/@google-cloud/promisify/build/src/index.js:71:28)
    at new Promise (<anonymous>)
    at Table.wrapper (XXXXXXXXX/node_modules/@google-cloud/bigquery/node_modules/@google-cloud/promisify/build/src/index.js:56:16)
    at Object.<anonymous> (XXXXXXXXX/lib/system/ImportFirestoreToBigQuery.js:35:22)
    at Generator.next (<anonymous>)
    at XXXXXXXX/lib/system/ImportFirestoreToBigQuery.js:7:71
```

I am a bit surprise because i can do it from the [console](https://cloud.google.com/bigquery/docs/loading-data-cloud-firestore) and the jobs created used `DATASTORE_BACKUP`
![Screen Shot 2019-05-22 at 12 58 40 PM](https://user-images.githubusercontent.com/915359/58193731-ab722f00-7c91-11e9-9cba-a42531ad4efd.png)

Am I missing anything?

**Comment by callmehiphop** [comment]
Looks like the client doesn't support that source format at the moment.

@stephenplusplus WDYT about removing the source format whitelisting?

**Comment by stephenplusplus** [comment]
That seems like the right thing to do.
