### ISSUE TITLE
table.getRows call with start index and max results errors with: invalid distance too far back

### ISSUE THREAD

**Issue by filmaj** [googleapis/nodejs-bigquery#562]
Thanks for stopping by to let us know something could be better!

Please run down the following list and make sure you've tried the usual "quick fixes":

- [x] Search the issues already opened: https://github.com/googleapis/nodejs-bigquery/issues
- [x] Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
- [x] Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: Red Hat Enterprise Linux Server release 7.6 (Maipo)
  - Node.js version: 10.10.0
  - npm version: 6.4.1
  - `@google-cloud/bigquery` version: 4.3.0

#### Steps to reproduce

  1. `table.getRows({startIndex:1158305, maxResults:5000}).then(function(data) { console.log(│
data) });` yields:

```
Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events:
      { removeListener: [Function: updateExceptionCapture],
        newListener: [Function: updateExceptionCapture],
        error: [Function: debugDomainError] },
     _eventsCount: 3,
     _maxListeners: undefined,
     members: [] } }
> (node:8452) UnhandledPromiseRejectionWarning: FetchError: Invalid response body while trying to fetch https://bigquery.googleapis.com/bigquery/v2/projects/public-github-adobe/datasets/github_archive_query_views/tables/users_pushes_2019_08/data?startIndex=1158305&maxResults=5000: invalid distance too far back
    at Gunzip.<anonymous> (/home/dxbot/oss-contributors/node_modules/node-fetch/lib/index.js:399:12)
    at Gunzip.emit (events.js:187:15)
    at Gunzip.EventEmitter.emit (domain.js:442:20)
    at Zlib.zlibOnError [as onerror] (zlib.js:156:8)
```

Hopefully you have access to the project `public-github-adobe`, dataset `github_archive_query_views` and table `users_pushes_2019_08` (it should be public for authenticated users). The URL for this is: https://console.cloud.google.com/bigquery?project=public-github-adobe&p=public-github-adobe&d=github_archive_query_views&t=users_pushes_2019_08&page=table
The table in question has about 1.5 million rows so I don't think this is an out-of-bounds error related to the start index and max results parameters.

Thanks in advance for any pointers!

**Comment by callmehiphop** [comment]
@filmaj sorry to hear you're running into this, I've attempted to recreate this on my local machine but it seems to be working as expected.

My reproduction is pretty barebones, are there any additional steps I can take that might help to reproduce?

```js
const {BigQuery} = require('@google-cloud/bigquery');

const projectId = 'public-github-adobe';
const bq = new BigQuery({projectId});
const table = bq
  .dataset('github_archive_query_views')
  .table('users_pushes_2019_08');

table.getRows({startIndex:1158305, maxResults:5000})
  .then(data => console.log(data))
  .catch(err => console.error(err));
```

@shollyman @tswast any ideas why we might be seeing an `invalid distance too far back` error here?

**Comment by filmaj** [comment]
Hmm, yeah on my Mac machine it works fine. Perhaps this is OS and node-version specific? On Mac OS 10.13.6 w/ node 10.15.3 your above code works fine a well.

I used your exact code to run on my RHEL 7 machine (where I do a bunch of bigquery work / data crunching) and got the same error, but  here's the full output in case that's helpful:

```
{ FetchError: Invalid response body while trying to fetch https://bigquery.googleapis.com/bigquery/v2/projects/public-github-adobe/datasets/github_archive_query_views/tables/users_pushes_2019_08/data?startIndex=1158305&maxResults=5000: invalid distance too far back
    at Gunzip.<anonymous> (/home/dxbot/oss-contributors/node_modules/node-fetch/lib/index.js:399:12)
    at Gunzip.emit (events.js:187:15)
    at Zlib.zlibOnError [as onerror] (zlib.js:156:8)
  message:
   'Invalid response body while trying to fetch https://bigquery.googleapis.com/bigquery/v2/projects/public-github-adobe/datasets/github_archive_query_views/tables/users_pushes_2019_08/data?startIndex=1158305&maxResults=5000: invalid distance too far back',
  type: 'system',
  errno: 'Z_DATA_ERROR',
  code: 'Z_DATA_ERROR',
  response:
   Gunzip {
     _readableState:
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: BufferList { length: 0 },
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        emitClose: true,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: true,
     _events:
      { prefinish: [Function: prefinish],
        end: [Array],
        error: [Array],
        data: [Function] },
     _eventsCount: 4,
     _maxListeners: undefined,
     _writableState:
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 14786,
        writing: true,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: [Function: nop],
        writelen: 1389,
        bufferedRequest: [Object],
        lastBufferedRequest: [Object],
        pendingcb: 52,
        prefinished: false,
        errorEmitted: false,
        emitClose: true,
        bufferedRequestCount: 51,
        corkedRequestsFree: [Object] },
     writable: true,
     allowHalfOpen: true,
     _transformState:
      { afterTransform: [Function: bound afterTransform],
        needTransform: true,
        transforming: true,
        writecb: [Function: bound onwrite],
        writechunk:
         <Buffer e2 1b af e1 08 fb e6 9b 96 86 b2 49 3b 38 0c 49 a4 cb 2b 0e 34 c0 6b 76 1c 7c b9 51 56 1c 3e 0b 7b 47 e9 03 05 b8 97 e8 49 e8 cd 3d 48 81 ba 0d 7c ed ... >,
        writeencoding: 'buffer' },
     bytesWritten: 778,
     _handle: null,
     _hadError: true,
     _writeState: Uint32Array [ 9288, 0 ],
     _outBuffer:
      <Buffer 7b 0a 20 20 22 6b 69 6e 64 22 3a 20 22 62 69 67 71 75 65 72 79 23 74 61 62 6c 65 44 61 74 61 4c 69 73 74 22 2c 0a 20 20 22 65 74 61 67 22 3a 20 22 39 ... >,
     _outOffset: 7096,
     _level: -1,
     _strategy: 0,
     _chunkSize: 16384,
     _flushFlag: 2,
     _scheduledFlushFlag: 0,
     _origFlushFlag: 2,
     _finishFlushFlag: 2,
     _info: undefined,
     statusCode: 200,
     statusMessage: 'OK',
     request:
      { agent: [Agent],
        headers: [Object],
        href:
         'https://bigquery.googleapis.com/bigquery/v2/projects/public-github-adobe/datasets/github_archive_query_views/tables/users_pushes_2019_08/data?startIndex=1158305&maxResults=5000' },
     body: [Circular],
     headers:
      { 'alt-svc':
         'quic=":443"; ma=2592000; v="46,43",h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000',
        'cache-control': 'private',
        'content-encoding': 'gzip',
        'content-type': 'application/json; charset=UTF-8',
        date: 'Wed, 23 Oct 2019 14:30:05 GMT',
        etag: '9+ajHsZwsylyYsGm9hU2dQ==',
        server: 'ESF',
        'transfer-encoding': 'chunked',
        vary: 'Origin, X-Origin, Referer',
        'x-frame-options': 'SAMEORIGIN',
        'x-xss-protection': '0' },
     toJSON: [Function: toJSON] } }
```

It looks like the response returned 200 from bigquery, so the error is happening on the RHEL when trying to decompress the gzip'ed response? Bizarre...
