### ISSUE TITLE
keyFilename in BQ constructor is not enough to authenticate API calls

### ISSUE THREAD

**Issue by sofisl** [googleapis/nodejs-bigquery#936]
When a user instantiates a client with just a `keyFilename`, an error pops up saying that a project ID is required. 

So, for example: 
```
  const bigquery = new BigQuery({
    keyFilename:
      PATH_TO_KEYFILE,
  });
```

returns:
```
Error: Sorry, we cannot connect to Cloud Services without a project
 ID. You may specify one with an environment variable named
 "GOOGLE_CLOUD_PROJECT".
    at Object.replaceProjectIdToken (/Users/sofialeon/gcp/nodejs-bigquery/samples/node_modules/@google-cloud/projectify/build/src/index.js:46:19)
    at Util.decorateRequest (/Users/sofialeon/gcp/nodejs-bigquery/samples/node_modules/@google-cloud/common/build/src/util.js:484:36)
    at onAuthenticated (/Users/sofialeon/gcp/nodejs-bigquery/samples/node_modules/@google-cloud/common/build/src/util.js:335:53)
    at /Users/sofialeon/gcp/nodejs-bigquery/samples/node_modules/@google-cloud/common/build/src/util.js:381:21
```

In other client libraries, this should be a sufficient method for providing authentication. See [this bug](https://github.com/googleapis/google-auth-library-nodejs/issues/1084) for more details on the investigation.

**Comment by stephenplusplus** [comment]
PR sent over in the common library: https://github.com/googleapis/nodejs-common/pull/663
